version: "3.8"
services:
  # react development server
  client:
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - "3000:3000"
  # server container manages client requests
  server:
    build:
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - "9000:9000"
      # localhost:9000/ for host machine
      # server:9000/ for containers
    volumes:
      - userdata:/storage # mounted volume, contains user generated data
  # executor container responds to requests from the server container
  executor:
    build:
      context: ./executor
      dockerfile: executor.dockerfile
    # visible as executor:8080/ for other containers, but the app is hidden to the host
    volumes:
      - userdata:/storage # mounted volume, contains user generated data

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo:27017/

volumes:
  # userdata volume common to all composed containers
  userdata:
    external: true
  mongodbdata:
    external: true
