export const config = {
  configOverwrite: {
    startWithAudioMuted: true,
    disableInviteFunctions: true,
    logoClickUrl: "",
    logoImageUrl: "",
    prejoinPageEnabled: false, //This here
    toolbarButtons: [
      "camera",
      "chat",
      //   "closedcaptions",
      "desktop",
      "etherpad",
      "filmstrip",
      //   "fullscreen",
      "hangup",
      "help",
      //   "invite",
      "microphone",
      //   "mute-everyone",
      //   "mute-video-everyone",
      "participants-pane",
      //   "raisehand",
      //   "recording",
      // 'security',
      //   "select-background",
      // 'settings',
      "shareaudio",
      "sharedvideo",
      "shortcuts",
      //   "tileview",
      "toggle-camera",
      "videoquality",
      "__end",
    ],
  },
  interfaceConfigOverwrite: {
    DEFAULT_BACKGROUND: "#252525",
    HIDE_INVITE_MORE_HEADER: true,
    SHARING_FEATURES: [],
    SHOW_PROMOTIONAL_CLOSE_PAGE: false,
    AUDIO_LEVEL_PRIMARY_COLOR: "#7bfffb",
    AUDIO_LEVEL_SECONDARY_COLOR: "#00c9c2",
    DEFAULT_LOGO_URL: "",
    JITSI_WATERMARK_LINK: "",
    SHOW_JITSI_WATERMARK: false,
    SHOW_WATERMARK_FOR_GUESTS: false,
  },
}
